language: node_js
node_js:
  - 14

cache: npm

script: npm run test:unit

before_deploy: npm run build

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: pages
  fqdn: lancelotblanchard.com
  on:
    branch: main
